public class help {
    Public string evenNumber(){
        integer x=9;
        string b;
       
        if(math.mod(x, 2) == 0){
        b='even number true';
        }
        else{
            b='even number false';
                }
             return b;
    }
    public string oddNumber(){
        Integer y = 9;
        string c;
if(math.mod(y, 2) != 0){
    c='odd number true';
}
else
{
    c='odd number false';
}
        return c;
       
    

}
    
}